In [24]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
from sklearn.externals import joblib
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn import metrics

In [25]:
#Loading the complete File

In [26]:
irisCompleteData= pd.read_csv("C:/MyFolder/iris.csv")

In [27]:
#In the file we have total 148 records. From these records we have decided to keep 140 for training purpose.

In [28]:
trainData = irisCompleteData.head(140)

In [29]:
print("Dimensions of train: {}".format(trainData.shape))


Dimensions of train: (140, 5)


In [30]:
#The reamining 8 records will be used for testing purpose.

In [31]:
untouchedTestData = irisCompleteData.tail(8)

In [33]:
print(len(trainData))

140


In [34]:
print(len(untouchedTestData))

8


In [35]:
#From the test records, we are deleting the 'class' columns.
#ONE THING IMPORTANT IS THAT WE ARE NOT DELETING FROM THE ACTUAL FILE BUT FROM THE DATAFRAME.
#ANOTHER IMPORTANT THING IS THAT- HERE WE HAVE ONE FILE WHICH WE HAVE DIVIDED INTO TWO DATAFRAMES.
#IF WE WERE GIVEN TWO FILES (TEST & TRAIN) WE COULD HAVE SIMPLY LOADED BOTH OF THEM INTO TWO DIFFERENT DATAFRAMES.
#ONE FILE | TWO FILE APPROACH MAKES NO DIFFERENCE ! 

In [36]:
del untouchedTestData['class']

In [37]:
print("Dimensions of test: {}".format(untouchedTestData.shape))

Dimensions of test: (8, 4)


In [38]:
# Right now our Training Dataframe is of (120, 5) dimention.
# and our Testing Dataframe is of (28, 4) dimention.

#Now, we are going introduce 3 new columns (in both Training and Testing Dataframes)
#3 new columns will be for class.Default values = 0  [SPARSE MATRIX WAY !!!]

In [39]:
new_age_columns = ["Iris-setosa","Iris-versicolor","Iris-virginica"]

for newCol in new_age_columns:
    trainData[newCol] =0
    
for newCol in new_age_columns:
    untouchedTestData[newCol] =0
    


C:\Users\rvaish\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\rvaish\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


In [40]:
print("Dimensions of train: {}".format(trainData.shape))

Dimensions of train: (140, 8)


In [41]:
print("Dimensions of train: {}".format(untouchedTestData.shape))

Dimensions of train: (8, 7)


In [42]:
#Now as for 3 newly created columns we have assigned 0 as default values ; but that's not going to take things forward.
#We need to assign respective values into the same.


In [43]:
trainData['Iris-setosa'] = np.where(trainData['class']==1, '1', '0')
trainData['Iris-versicolor'] = np.where(trainData['class']==2, '1', '0')
trainData['Iris-virginica'] = np.where(trainData['class']==3, '1', '0')

C:\Users\rvaish\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\rvaish\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\rvaish\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_ind

In [44]:
#Now choose the important variables (columns)

In [45]:
selectdColumns = ["sepallength","sepalwidth","petallength","petalwidth","Iris-setosa","Iris-versicolor","Iris-virginica"]

In [46]:
# Now we have Sparse Matrix is prepared, time to apply ML modeling.

In [47]:
lr = GaussianNB()

In [48]:
lr.fit(trainData[selectdColumns], trainData["class"])

GaussianNB(priors=None)

In [49]:
print(len(trainData))

140


In [50]:
print(len(untouchedTestData))

8


In [54]:
all_X = trainData[selectdColumns]
all_y = trainData['class']

train_X, test_X, train_y, test_y = train_test_split(
    all_X, all_y, test_size=0.20,random_state=0)

lr.fit(train_X, train_y)
predictions = lr.predict(test_X)
print(predictions)
print(len(predictions))





[1 1 3 3 3 1 2 2 2 3 1 3 1 3 1 1 1 2 2 3 2 2 2 1 1 1 1 1 1 2 3 2 1 1 3]
35


In [55]:

scores = cross_val_score(lr, all_X, all_y, cv=10)
scores.sort()
accuracy = scores.mean()

print(scores)
print(accuracy)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1.0


In [56]:
holdout = untouchedTestData 

In [58]:
predictions = lr.predict(holdout[selectdColumns])

In [59]:
print(predictions)

[3 3 3 3 3 3 3 3]
